// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN95xkQEGwXRmsy_u7tPRedxBETl5kaiU',
    appId: '1:137250705047:web:6155719a83f1d99d77e3d2',
    messagingSenderId: '137250705047',
    projectId: 'todo-215f5',
    authDomain: 'todo-215f5.firebaseapp.com',
    storageBucket: 'todo-215f5.firebasestorage.app',
    measurementId: 'G-H9RDXJJ16J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHZkqDeDRCNSrzy0eZUqqhuRJbzsc1tkI',
    appId: '1:137250705047:android:02dd65946b9c1e5177e3d2',
    messagingSenderId: '137250705047',
    projectId: 'todo-215f5',
    storageBucket: 'todo-215f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxb9RaQoMAh_vFHnZSa0KosL05UITdtns',
    appId: '1:137250705047:ios:f90486739b63207677e3d2',
    messagingSenderId: '137250705047',
    projectId: 'todo-215f5',
    storageBucket: 'todo-215f5.firebasestorage.app',
    iosBundleId: 'com.example.toDoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxb9RaQoMAh_vFHnZSa0KosL05UITdtns',
    appId: '1:137250705047:ios:f90486739b63207677e3d2',
    messagingSenderId: '137250705047',
    projectId: 'todo-215f5',
    storageBucket: 'todo-215f5.firebasestorage.app',
    iosBundleId: 'com.example.toDoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN95xkQEGwXRmsy_u7tPRedxBETl5kaiU',
    appId: '1:137250705047:web:a00f7d7cc13832ba77e3d2',
    messagingSenderId: '137250705047',
    projectId: 'todo-215f5',
    authDomain: 'todo-215f5.firebaseapp.com',
    storageBucket: 'todo-215f5.firebasestorage.app',
    measurementId: 'G-1X7ENL0S0T',
  );
}
